# Generated by Django 3.1.1 on 2020-11-23 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('Can_Librarian', 'Set Librarian'),)},
        ),
    ]
